![resim](https://github.com/yaagmurss/AdvancedRPADeveloperCertificationTrainingNotes/assets/52479605/bfe877e2-8ee3-4a9f-ae00-d53ed7f35fd2)


![resim](https://github.com/yaagmurss/AdvancedRPADeveloperCertificationTrainingNotes/assets/52479605/7d78dcb7-7d17-4e1c-914e-0c5886e49312)

---

***System exceptions***

- The unexpected exceptions are the one known as System Exceptions (SE). 
- They belong to the .NET framework and are categorized under the System.Exception class.
- Proper handling should be in place for these kinds of exceptions and they can cause the process to fail.

- ***NullReferenceException*** —Occurs when using a variable with no set value (not initialized).    2

- ***IndexOutOfRangeException*** —Occurs when the index of an object is out of the limits of the collection.    3

- ***ArgumentException***—Is thrown when a method is invoked and at least one of the passed arguments doesn't meet the parameter specification of the called method.    4

- ***SelectorNotFoundException*** Is thrown when the robot is unable to find the specified selector for an activity in the target app within the Timeout period. As you know, the timeout property specifies the amount of time, in seconds, that the system will wait for an operation to finish before generating an error.

  ***ImageOperationException*** —Occurs when an image isn't found within the Timeout period.

- ***TextNotFoundException*** —Occurs when the indicated text isn't found within the Timeout period.

- ***ApplicationException*** —Describes an error rooted in a technical issue, such as an application that isn't responding.


---

***Business exceptions***

- Business Rule Exceptions (BRE) aren't automatically generated as system exceptions. They must be defined by a developer by using the Throw Activity and handled inside a TryCatch. 

---

- The Try Catch mechanism runs the activities within the Try block, and if an error occurs, it proceeds to execute the activities within the Catches block.
- The Finally block, on the other hand, is executed only when no exceptions are thrown or when an exception is caught and handled within the Catches block without being re-thrown.
- This mechanism allows for structured error handling and ensures that the Finally block is executed in scenarios where no unhandled exceptions are encountered










  
